/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

export interface Order {
  /**
  * A unique ID for the order.
  */
  id?: string;
  /**
  * The order creation date (string).
  */
  dateCreated?: string;
  /**
  * A string describing the order status.
  */
  status?: string;
  /**
  * The name of a Bootstrap icon for the status (without the "bi-" prefix).
  */
  statusIcon?: string;
  /**
  * The name of  a Bootstrap color that represents the order's status (without the "text-" or "bg-"
  * prefix). 
  */
  statusColor?: string;
}
