/**
 * Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
 * Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
 *
 * Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
 */

/**
 * User information
 */
export interface User {
  id?: number;
  email?: string;
  firstName?: string;
  surname?: string;
  password?: string;
  creationDate?: Date;
  admin?: boolean;
}

export interface Order {
  /**
   * A unique ID for the order.
   */
  id?: string;
  /**
   * The order creation date (string).
   */
  dateCreated?: string;
  /**
   * A string describing the order status.
   */
  status?: string;
  /**
   * The name of a Bootstrap icon for the status (without the "bi-" prefix).
   */
  statusIcon?: string;
  /**
   * The name of  a Bootstrap color that represents the order's status (without the "text-" or "bg-"
   * prefix).
   */
  statusColor?: string;
}

import { Authorization } from '@shared/dto/group/authorization.enum';

/**
 * Represents a user group in the system
 */
export interface Group {
  id?: number;
  name?: string;
  description?: string;
}

/**
 * Represents authorization/permission levels for a group on a problem
 */
export interface GroupAuthorization {
  id?: number;
  group?: Group;
  authorizationLevel?: Authorization;
  grantedDate?: Date;
}

/**
 * A general problem of any kind to be solved
 */
export interface Problem {
  id?: number;
  name?: string;
  description?: string;
  status?: string;
  open?: string;
  creationDate?: Date;
  creator?: User;
  groupAuthorizations?: GroupAuthorization[];
}
