/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';
import { LocaleService } from '../../services/locale.service';

@Component({
  selector: 'app-header',
  standalone: true,
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  imports: [RouterLink, NgbDropdownModule, CommonModule]
})
export class HeaderComponent {
  private readonly localeService: LocaleService = inject(LocaleService);

  constructor() {}

  public onHyperlink4Click($event: MouseEvent): void {
    $event.preventDefault();
  }

  public navigateToHome(): void {
    void this.localeService.navigateWithLocale([]);
  }
}
