/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { LocaleService } from '../../services/locale.service';

@Component({
  selector: 'app-side-bar',
  standalone: true,
  templateUrl: './side-bar.component.html',
  styleUrls: ['./side-bar.component.scss'],
  imports: [RouterLink, RouterLinkActive, CommonModule]
})
export class SideBarComponent {
  private readonly localeService: LocaleService = inject(LocaleService);

  constructor() {}

  /**
   * Expose current locale signal for template usage.
   */
  public currentLocale(): string {
    return this.localeService.currentLocale();
  }
}
