/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-orders-shipped',
  standalone: true,
  templateUrl: './orders-shipped.component.html',
  styleUrls: ['./orders-shipped.component.scss'],
  imports: [CommonModule]
})
export class OrdersShippedComponent {

  constructor() {}
}
