/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Order } from '../../../model';

@Component({
  selector: 'app-orders-card',
  standalone: true,
  templateUrl: './orders-card.component.html',
  imports: [RouterLink, CommonModule]
})
export class OrdersCardComponent {
  @Input() public title: string | null = '';

  @Input() public orders: Order[] | null = [];

  constructor() {}

  protected getIcon2Classes(ordersItem: Order): string[] {
    const result = [];
    if (ordersItem.statusColor) { result.push(`text-${ordersItem.statusColor}`); }
    if (ordersItem.statusIcon) { result.push(`bi-${ordersItem.statusIcon}`); }
    return result;
  }
}
