/**
 * Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
 * Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
 *
 * Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
 */

import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { NgbAlertModule, NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';
import { routes } from './app.routes';
import {
  HttpClient,
  provideHttpClient,
} from '@angular/common/http';
import { ProblemService } from './services/problem.service';
import { DBProblemService } from './services/backend.problem.service';


export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    importProvidersFrom(
      NgbAlertModule,
      NgbDropdownModule,
      BrowserModule
    ),
    provideRouter(routes),
    { provide: ProblemService, useClass: DBProblemService },
  ],
};
