/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/Components/header.component';
import { SideBarComponent } from './components/Components/side-bar.component';
import { ToastContainerComponent } from './components/Components/Common/toast-container.component';
import { ThemeService } from './services/theme.service';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  imports: [HeaderComponent, SideBarComponent, ToastContainerComponent, RouterOutlet, CommonModule]
})
export class AppComponent implements OnInit {
  private readonly themeService: ThemeService = inject(ThemeService);

  constructor() {}

  /**
   * Initializes the theme on application startup.
   */
  public ngOnInit(): void {
    this.themeService.initializeTheme();
  }
}
