/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { NgbAlertModule } from '@ng-bootstrap/ng-bootstrap';
import { Order } from '../../model';
import { OrderActionsComponent } from '../Components/Orders/order-actions.component';
import { OrdersCardComponent } from '../Components/Orders/orders-card.component';
import { OrdersShippedComponent } from '../Components/Orders/orders-shipped.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
  imports: [NgbAlertModule, OrderActionsComponent, OrdersShippedComponent, OrdersCardComponent, CommonModule]
})
export class DashboardComponent {
  public showAlert: boolean = true;

  public sampleOrders: Order[] = [
    {
      id: '145790',
      dateCreated: '14/03/24',
      status: 'Pending',
      statusIcon: 'hourglass',
      statusColor: 'secondary'
    },
    {
      id: '145789',
      dateCreated: '14/03/24',
      status: 'Pending',
      statusIcon: 'hourglass',
      statusColor: 'secondary'
    },
    {
      id: '145788',
      dateCreated: '13/03/24',
      status: 'Shipped',
      statusIcon: 'truck',
      statusColor: 'success'
    },
    {
      id: '145787',
      dateCreated: '13/03/24',
      status: 'Pending',
      statusIcon: 'hourglass',
      statusColor: 'secondary'
    },
    {
      id: '145786',
      dateCreated: '13/03/24',
      status: 'Out for delivery',
      statusIcon: 'box2',
      statusColor: 'warning'
    }
  ];

  constructor() {}

  public onAlert1Closed(): void {
    this.showAlert = false;
  }
}
