/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ContentPlaceholderComponent } from '../Components/content-placeholder.component';

@Component({
  selector: 'app-find-problem-outlet',
  standalone: true,
  templateUrl: './find-problem-outlet.component.html',
  imports: [ContentPlaceholderComponent, CommonModule]
})
export class FindProblemOutletComponent {

  constructor() {}
}
