/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component, inject, Input } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { ProblemFormComponent } from '../Components/Problem/problem-form.component';
import { Problem } from '../../model';

@Component({
  selector: 'app-problem-add',
  standalone: true,
  templateUrl: './problem-add.component.html',
  imports: [ProblemFormComponent, CommonModule]
})
export class ProblemAddComponent {
  private activeModal = inject(NgbActiveModal);

  @Input() initialValue: Problem | null = null;
  @Input() isEditMode: boolean = false;

  public onProblemSubmit(problem: Problem): void {
    this.activeModal.close(problem);
  }

  public onCancel(): void {
    this.activeModal.dismiss('cancel');
  }

  public triggerFormSubmit(): void {
    // Find the form element and trigger submit
    const formElement = document.querySelector('app-problem-form form') as HTMLFormElement;
    if (formElement) {
      formElement.requestSubmit();
    }
  }

  public getModalTitle(): string {
    return this.isEditMode ? $localize`Edit Problem` : $localize`Create New Problem`;
  }

  public getSubmitButtonLabel(): string {
    return this.isEditMode ? $localize`Update Problem` : $localize`Create Problem`;
  }
}
