/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ProblemFormComponent } from '../Components/Problem/problem-form.component';

@Component({
  selector: 'app-problem-add',
  standalone: true,
  templateUrl: './problem-add.component.html',
  imports: [ProblemFormComponent, CommonModule]
})
export class ProblemAddComponent {

  constructor() {}
}
