/**
 * Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
 * Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
 *
 * Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
 */

import { inject, Injectable, signal } from '@angular/core';
import { Problem } from '../model';
import { problem_list_mock } from './problem.service.mock-data';
import { catchError, map, Observable, of, tap, throwError } from 'rxjs';
import { HttpClient } from '@angular/common/http';

@Injectable({ providedIn: 'root' })
export class ProblemService {
  /**
   * fetch problems which groups of user has authorization to work on
   */
  public fetchProblemsOfUserGroups(): Observable<Problem[]> {
    return of(
      problem_list_mock.sort((a, b) => {
        return a.id! - b.id!;
      })
    );
  }
}
