/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Soluce, at https://www.jitblox.com/project/5JHnGKTPaU/soluce
*/

import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';
import { importProvidersFrom, Provider } from '@angular/core';
import { provideClientHydration } from '@angular/platform-browser';
import { SupportedLocaleCode } from './app/interfaces/locale-config.interface';

// Configure locale detection and i18n
const locale: SupportedLocaleCode = getLocaleFromUrl() || 'en-EN';

bootstrapApplication(AppComponent, {
  ...appConfig,
  providers: [
    ...appConfig.providers,
    provideClientHydration()
  ]
})
  .catch(err => console.error(err));

/**
 * Extract locale from current URL.
 * @returns The locale from URL or null if not found.
 */
function getLocaleFromUrl(): SupportedLocaleCode | null {
  if (typeof window === 'undefined') {
    return null;
  }

  const pathSegments: string[] = window.location.pathname.split('/').filter(segment => segment.length > 0);
  if (pathSegments.length === 0) {
    return null;
  }

  const firstSegment: string = pathSegments[0];
  const supportedLocales: ReadonlyArray<SupportedLocaleCode> = ['en-EN', 'fr-FR'] as const;
  
  if (supportedLocales.includes(firstSegment as SupportedLocaleCode)) {
    return firstSegment as SupportedLocaleCode;
  }

  return null;
}
